// Generated by polka.codes
// This file implements the AnalyzerAgent class for project analysis

import { getAvailableTools } from '../../getAvailableTools'
import { PermissionLevel } from '../../tool'
import { allTools } from '../../tools'
import { AgentBase, type AgentInfo, type SharedAgentOptions } from '../AgentBase'
import { fullSystemPrompt } from './prompts'

export type AnalyzerAgentOptions = SharedAgentOptions

export class AnalyzerAgent extends AgentBase {
  constructor(options: AnalyzerAgentOptions) {
    const combinedTools = [...(options.additionalTools ?? []), ...Object.values(allTools)]
    const tools = getAvailableTools(options.provider, combinedTools, (options.agents?.length ?? 0) > 0, PermissionLevel.Read)
    const toolNamePrefix = 'tool_'
    const systemPrompt = fullSystemPrompt(
      {
        os: options.os,
      },
      tools,
      toolNamePrefix,
      options.customInstructions ?? [],
      options.scripts ?? {},
      options.interactive,
    )

    super(analyzerAgentInfo.name, options.ai, {
      systemPrompt,
      tools,
      toolNamePrefix,
      provider: options.provider,
      interactive: options.interactive,
      agents: options.agents,
      scripts: options.scripts,
      callback: options.callback,
    })
  }

  override onBeforeInvokeTool() {
    return Promise.resolve(undefined)
  }
}

export const analyzerAgentInfo = {
  name: 'analyzer',
  responsibilities: [
    'Analyzing project structure and organization',
    'Identifying key source code files and their relationships',
    'Understanding common coding patterns and conventions',
    'Examining development workflow and tooling',
    'Analyzing dependencies and their usage patterns',
  ],
} as const satisfies AgentInfo
