// Generated by polka.codes
// This file implements the AnalyzerAgent class for project analysis

import { getAvailableTools } from '../../tool'
import { askFollowupQuestion, attemptCompletion, handOver, listCodeDefinitionNames, listFiles, readFile, searchFiles } from '../../tools'
import { AgentBase, type AgentInfo, type SharedAgentOptions } from '../AgentBase'
import { fullSystemPrompt } from './prompts'

export type AnalyzerAgentOptions = SharedAgentOptions

export class AnalyzerAgent extends AgentBase {
  constructor(options: AnalyzerAgentOptions) {
    const agentTools = [
      ...(options.additionalTools ?? []),
      askFollowupQuestion,
      attemptCompletion,
      handOver,
      listCodeDefinitionNames,
      listFiles,
      readFile,
      searchFiles,
    ] // readonly tools
    const tools = getAvailableTools(options.provider, agentTools)
    const toolNamePrefix = 'tool_'
    const systemPrompt = fullSystemPrompt(
      {
        os: options.os,
      },
      tools,
      toolNamePrefix,
      options.customInstructions ?? [],
      options.scripts ?? {},
      options.interactive,
    )

    super(analyzerAgentInfo.name, options.ai, {
      systemPrompt,
      tools,
      toolNamePrefix,
      provider: options.provider,
      interactive: options.interactive,
      agents: options.agents,
    })
  }
}

export const analyzerAgentInfo = {
  name: 'analyzer',
  responsibilities: [
    'Analyzing project structure and organization',
    'Identifying key source code files and their relationships',
    'Understanding common coding patterns and conventions',
    'Examining development workflow and tooling',
    'Analyzing dependencies and their usage patterns',
  ],
} as const satisfies AgentInfo
