// Test for plan tool formatting (MCP server)
// generated by polka.codes

import { describe, expect, test } from 'bun:test'

describe('MCP Plan Tool Formatting', () => {
  test('should format plan result with file paths only', () => {
    // Simulate the result from planWorkflow
    const mockPlanResult = {
      plan: 'Implement feature X\n1. Step 1\n2. Step 2',
      files: [
        { path: 'src/feature.ts', content: 'very long content...' },
        { path: 'src/test.ts', content: 'more content...' },
        { path: 'src/types.ts', content: 'even more content...' },
      ],
    }

    // Simulate the MCP formatting logic
    let output = ''
    if (mockPlanResult.plan) {
      output += mockPlanResult.plan
    }

    if (mockPlanResult.files && mockPlanResult.files.length > 0) {
      output += '\n\nFiles to modify:\n'
      // Extract only the file paths, not the content
      output += mockPlanResult.files.map((f) => `  - ${f.path}`).join('\n')
    }

    const expected = `Implement feature X
1. Step 1
2. Step 2

Files to modify:
  - src/feature.ts
  - src/test.ts
  - src/types.ts`

    expect(output).toBe(expected)
    expect(output).not.toContain('content')
    expect(output).not.toContain('very long')
  })

  test('should handle plan result with no files', () => {
    const mockPlanResult = {
      plan: 'Simple plan with no files',
    }

    let output = ''
    if (mockPlanResult.plan) {
      output += mockPlanResult.plan
    }

    expect(output).toBe('Simple plan with no files')
  })

  test('should handle plan result with question', () => {
    const mockPlanResult = {
      question: {
        question: 'Should we use library A or B?',
        defaultAnswer: 'Library A',
      },
    }

    // Simulate the MCP formatting logic for questions
    if (mockPlanResult.question) {
      const output = JSON.stringify({ question: mockPlanResult.question }, null, 2)
      const parsed = JSON.parse(output)

      expect(parsed).toHaveProperty('question')
      expect(parsed.question.question).toBe('Should we use library A or B?')
    }
  })

  test('should handle plan result with reason (no plan needed)', () => {
    const mockPlanResult = {
      reason: 'This is already implemented',
    }

    // Simulate the MCP formatting logic
    let output = ''
    if (mockPlanResult.reason) {
      output = `No plan needed: ${mockPlanResult.reason}`
    }

    expect(output).toBe('No plan needed: This is already implemented')
  })
})
