/**
 * Chat command implementation
 * Generated by polka.codes
 */

import type { Command } from 'commander'
import { Chat } from '../Chat'
import { parseOptions } from '../options'

export async function runChat(_options: any, command: Command) {
  const { providerConfig } = parseOptions(command.opts())
  const chat = new Chat({
    onMessage: async (message: string) => {
      // TODO: Implement message handling
      console.log('Received message:', message)
      return 'Message received'
    },
    onExit: async () => {
      console.log('Chat session ended')
    },
  })
}
