// generated by polka.codes
import { Command } from 'commander'
import { createLogger } from '../logger'
import { runWorkflow } from '../runWorkflow'
import { type FixWorkflowInput, fixWorkflow } from '../workflows/fix.workflow'

export const fixCommand = new Command('fix')
  .description('Fix issues by running a command and letting an agent fix it.')
  .argument('[command]', 'The command to run')
  .option('-p, --prompt <prompt>', 'Additional prompt for the agent.')
  .action(async (command: string | undefined, options: { prompt?: string }, cmd: Command) => {
    const globalOpts = (cmd.parent ?? cmd).opts()
    const { verbose, yes } = globalOpts
    const workflowInput: FixWorkflowInput = { command, prompt: options.prompt }
    const logger = createLogger({
      verbose,
    })
    await runWorkflow(fixWorkflow, workflowInput, { commandName: 'fix', command: cmd, logger, yes })
  })
