// generated by polka.codes

import { Console } from 'node:console'
import { getProvider, type ProviderOptions, printEvent } from '@polka-codes/cli-shared'
import {
  combineHandlers,
  customStepSpecHandler,
  run,
  type SharedAgentOptions,
  sequentialStepSpecHandler,
  UsageMeter,
} from '@polka-codes/core'
import { Command } from 'commander'
import { merge } from 'lodash'
import ora from 'ora'
import { getModel } from '../getModel'
import { parseOptions } from '../options'
import prices from '../prices'
import { type ReviewWorkflowContext, reviewWorkflow } from '../workflows'
import { runTask } from './task'

const coreStepHandler = combineHandlers(customStepSpecHandler, sequentialStepSpecHandler)

export const reviewCommand = new Command('review')
  .description('Review a GitHub pull request or local changes')
  .option('--pr <pr>', 'The pull request number or URL to review')
  .option('--json', 'Output the review in JSON format', false)
  .action(async (options: { pr?: string; json: boolean }, command: Command) => {
    const parentOptions = command.parent?.opts() ?? {}
    const { providerConfig, config } = parseOptions(parentOptions)
    const commandConfig = providerConfig.getConfigForCommand('review')

    if (!commandConfig || !commandConfig.provider || !commandConfig.model) {
      console.error('Error: No provider specified. Please run "polka config" to configure your AI provider.')
      process.exit(1)
    }

    if (!options.json) {
      console.log('Provider:', commandConfig.provider)
      console.log('Model:', commandConfig.model)
    }

    const spinner = ora({
      text: 'Gathering information...',
      stream: process.stderr,
    }).start()

    const usage = new UsageMeter(merge(prices, config.prices ?? {}))
    const customConsole = options.json ? new Console(process.stderr, process.stderr) : console
    const onEvent = printEvent(parentOptions.verbose, usage, customConsole)
    const ai = getModel(commandConfig)
    const toolProviderOptions: ProviderOptions = {
      excludeFiles: parentOptions.config.excludeFiles,
    }
    const toolProvider = getProvider(toolProviderOptions)
    const sharedAiOptions = {
      ai,
      usageMeter: usage,
      os: process.platform,
      provider: toolProvider,
      policies: [],
      toolFormat: commandConfig.toolFormat,
      callback: parentOptions.verbose > 0 ? onEvent : undefined,
    } satisfies SharedAgentOptions

    const context: ReviewWorkflowContext = {
      ui: { spinner },
      agent: { sharedAiOptions },
      provider: toolProvider,
      parameters: parentOptions,
    }

    const input = { json: options.json, ...(options.pr && { pr: options.pr }) }

    try {
      const result = await run(reviewWorkflow, context, coreStepHandler, input)

      if (result.type === 'success') {
        if (result.output.shouldRunTask) {
          const taskInstruction = `please address the review result:

${result.output.formattedReview}`
          await runTask(taskInstruction, {}, command)
        }
      } else if (result.type === 'error') {
        if (result.error) {
          spinner.fail(`Error reviewing: ${result.error.message}`)
          console.error(result.error)
        } else {
          spinner.fail('Error reviewing: An unknown error occurred')
        }
        process.exit(1)
      }
    } catch (error) {
      spinner.fail(`Error reviewing: ${error instanceof Error ? error.message : String(error)}`)
      console.error(error)
      process.exit(1)
    } finally {
      if (!options.json) {
        usage.printUsage()
      }
    }
  })
