// generated by polka.codes

import type { z } from 'zod'
import type { PlainJson, ToolSignature } from '../workflow'

// Copied from @polka-codes/core/src/Agent/types.ts
export type AgentName = 'coder' | 'analyzer' | 'architect' | 'codefixer' | 'multi-agent'

export type InvokeAgentInput<T> = {
  agent: AgentName
  messages: (
    | string
    | {
        type: 'system' | 'user' | 'assistant'
        content: string
      }
  )[]
  outputSchema: z.ZodSchema<T>
}

export type InvokeAgentTool = ToolSignature<InvokeAgentInput<any>, PlainJson>
