agents:
  default:
    initialContext:
      excludes:
        - __snapshots__
        - .husky
  coder:
    hooks:
      beforeCompletion: bun fix; bun typecheck; bun test -u
excludeFiles:
  - .env
  - bun.lock
  - packages/cli/cli.mjs
scripts:
  test:
    command: bun test
    description: Run tests. Pass file path to run a specific test file.
  typecheck:
    command: bun typecheck
    description: |
      Check the code for type errors.
      Run this command after making changes to the code.
rules: |
  Use `bun` as the package manager
  When adding new dependencies, cd to the package directory and run `bun add <dependency>`
  Use `bun:test` to write tests. DO NOT use jest or mocha or vi
  DO NOT use mock in tests. Use spyOn imported bun 'bun:test' if needed
  When writing unit tests, use `.toMatchSnapshot()` if suitable
  When creating a new file, try to check if there are other files with similar content, and if so, read those files and use them as a reference
