agents:
  default:
    initialContext:
      excludes:
        - __snapshots__
        - .husky
        - packages/github/src/types/github-types.ts
excludeFiles:
  - .env
  - bun.lock
  - packages/cli/cli.mjs
  - packages/github/schema.docs.graphql
scripts:
  test: AGENT=1 bun test -u
  check: bun check
  format: bun fix
rules: |
  Use #methodName / #fieldName for private methods and fields
  Use `bun` as the package manager
  When adding new dependencies, cd to the package directory and run `bun add <dependency>`
  Use `bun:test` to write tests. DO NOT use jest or mocha or vi
  DO NOT use mock in tests. Use spyOn imported bun 'bun:test' if needed
  When writing unit tests, use `.toMatchSnapshot()` if suitable.
  In tests, ensure no redundant assertions. i.e. if `.toMatchSnapshot()` is used, then there is no need to have other assertions.
  NEVER mock modules
  Avoid unnecessary comments. Doc comments are not required when the code is self-explanatory.
  Use '.nullish()' instead of '.optional()' in zod schema unless there is a specific reason to use optional.
