scripts:
  format:
    command: bun fix
    description: Format code and fix lint issues
  check:
    command: bun check
    description: Typecheck and lint
  test:
    command: bun test
    description: Run tests
  build:
    command: bun build
    description: Build packages
commands:
  review:
    rules:
      - repo: polka-codes/prompts
        path: review/preamble.md
        branch: master
      - repo: polka-codes/prompts
        path: review/javascript.md
        branch: master
      - repo: polka-codes/prompts
        path: review/typescript.md
        branch: master
excludeFiles:
  - .env
  - .env.*
  - "*.pem"
  - "*.key"
  - .npmrc
