excludeFiles:
  - .env
  - packages/cli/cli.mjs
scripts:
  test:
    command: bun test
    description: Run tests. Pass file path to run a specific test file.
  check:
    command: bun check
    description: |
      Check the code for type errors and linting issues.
      Run this command after making changes to the code.
  format:
    command: bun fix
    description: |
      Format the code and fix fixable linting issues.
      Run this command when linting issues are found.
rules: |
  Use `bun` as the package manager
  When adding new dependencies, cd to the package directory and run `bun add <dependency>`
  Use `bun:test` to write tests. DO NOT use jest or mocha or vi
  DO NOT use mock in tests. Use spyOn imported bun 'bun:test' if needed
  When writing unit tests, use `.toMatchSnapshot()` if suitable
  When creating a new file, try to check if there are other files with similar content, and if so, read those files and use them as a reference
