// Generated by polka.codes

import { z } from 'zod'

/**
 * Base configuration patterns for reuse across different config types
 *
 * These provide single sources of truth for common configuration patterns,
 * reducing duplication and improving type safety through composition.
 */

/**
 * Base model configuration pattern
 * Used wherever a provider/model combination needs to be specified
 */
export const baseModelConfigSchema = z.object({
  provider: z.string().optional(),
  model: z.string().optional(),
  parameters: z.record(z.string(), z.unknown()).optional(),
})

export type BaseModelConfig = z.infer<typeof baseModelConfigSchema>

/**
 * Base approval configuration pattern
 */
export const baseApprovalConfigSchema = z.object({
  level: z.enum(['none', 'destructive', 'commits', 'all']).optional(),
  autoApprove: z.boolean().optional(),
  maxCost: z.number().positive().optional(),
})

export type BaseApprovalConfig = z.infer<typeof baseApprovalConfigSchema>

/**
 * Provider configuration (credentials and settings)
 * Separate from model selection - this is about auth and provider settings
 */
export const providerConfigSchema = z.object({
  apiKey: z.string().optional(),
  defaultModel: z.string().optional(),
  defaultParameters: z.record(z.string(), z.unknown()).optional(),
  location: z.string().optional(),
  project: z.string().optional(),
  keyFile: z.string().optional(),
  baseUrl: z.string().optional(),
  name: z.string().optional(),
})

export type ProviderConfig = z.infer<typeof providerConfigSchema>

/**
 * Model configuration with optional provider override
 * Combines base model config with budget and rules
 */
export const modelConfigSchema = baseModelConfigSchema.extend({
  budget: z.number().positive().optional(),
  rules: z.union([z.string(), z.array(z.string()).optional()]).optional(),
})

export type ModelConfig = z.infer<typeof modelConfigSchema>

/**
 * Helper to create a model config schema with tool-specific overrides
 * Used in MCP server tool configuration
 */
export const toolConfigSchema = z.union([
  z.boolean(), // Simple enable/disable
  baseModelConfigSchema, // Model override for this tool
])

export type ToolConfig = z.infer<typeof toolConfigSchema>
