// Generated by polka.codes
// Sample JavaScript file for testing tree-sitter parsing

function formatName(first, last) {
  return `${first} ${last}`
}

class Person {
  constructor(name) {
    this.name = name
  }

  greet() {
    return `Hello, ${this.name}!`
  }
}
