// generated by polka.codes
import { template } from 'lodash'
import type { Json, TemplatedString } from './types'

export const resolveTemplatedString = (
  templatedString: string | TemplatedString<{ [k: string]: Json }>,
  input: { [k: string]: Json },
): string => {
  if (typeof templatedString === 'string') {
    return templatedString
  }
  if (templatedString.type === 'function') {
    return templatedString.fn(input)
  }
  return template(templatedString.template)(input)
}
