// generated by polka.codes

import {
  agentWorkflow,
  type ExitReason,
  executeCommand,
  type FullToolInfo,
  fetchUrl,
  listFiles,
  readBinaryFile,
  readFile,
  removeFile,
  renameFile,
  replaceInFile,
  searchFiles,
  type WorkflowFn,
  writeToFile,
} from '@polka-codes/core'
import { z } from 'zod'
import type { CliToolRegistry } from '../workflow-tools'
import { type BaseWorkflowInput, getDefaultContext } from './workflow.utils'

export type TaskWorkflowInput = {
  task: string
  jsonMode?: boolean
}

const SYSTEM_PROMPT = `You are a generic AI assistant.
You are able to perform simple tasks including making simple changes, reading code, and answering user questions.
Use the available tools to perform the task.`

// Output schema for JSON mode - ensures the agent returns a JSON value
const TaskOutputSchema = z.any().describe('A JSON value with the task result')

export const taskWorkflow: WorkflowFn<TaskWorkflowInput & BaseWorkflowInput, ExitReason, CliToolRegistry> = async (input, context) => {
  const { logger, step } = context
  const { task, additionalTools, jsonMode } = input

  logger.info(`
Running generic agent...
`)

  const agentTools: FullToolInfo[] = [
    readFile,
    writeToFile,
    replaceInFile,
    searchFiles,
    listFiles,
    executeCommand,
    fetchUrl,
    readBinaryFile,
    removeFile,
    renameFile,
  ]

  if (additionalTools?.search) {
    agentTools.push(additionalTools.search)
  }
  if (additionalTools?.mcpTools) {
    agentTools.push(...additionalTools.mcpTools)
  }

  const result = await step('agent', async () => {
    const defaultContext = await getDefaultContext('task')
    const userMessage = `${task}\n\n${defaultContext}`
    return await agentWorkflow(
      {
        systemPrompt: SYSTEM_PROMPT,
        userMessage: [{ role: 'user', content: userMessage }],
        tools: agentTools,
        // In JSON mode, use outputSchema to ensure the agent returns JSON
        outputSchema: jsonMode ? TaskOutputSchema : undefined,
      },
      context,
    )
  })

  logger.info(`
Agent finished!
`)

  return result
}
