// generated by polka.codes

import { execSync } from 'node:child_process'
import { promises as fs } from 'node:fs'
import path from 'node:path'
import { type LoadedConfig, parseGitPorcelain, resolveRules } from '@polka-codes/cli-shared'
import type { ExitReason, FullToolInfo, Logger } from '@polka-codes/core'
import { z } from 'zod'
import { ApiProviderConfig } from '../ApiProviderConfig'
import { MissingDependencyError } from '../errors'
import type { WorkflowProgressCallback } from '../workflow-events'
import type { CliToolRegistry } from '../workflow-tools'

export type BaseWorkflowInput = {
  interactive: boolean
  additionalTools: {
    search?: FullToolInfo
    mcpTools?: FullToolInfo[]
  }
  config?: LoadedConfig
  onWorkflowProgress?: WorkflowProgressCallback
}

export function getAgentWorkflowFailureMessage(result: Exclude<ExitReason, { type: 'Exit' }>): string {
  return result.error.message
}

export type FileChange = {
  originalPath?: string
  path: string
  status: string
  insertions?: number
  deletions?: number
}

const changeDescriptions: Record<string, string> = { A: 'Added', M: 'Modified', D: 'Deleted', R: 'Renamed', C: 'Copied', T: 'Type changed' }

export function parseGitDiffNameStatus(output: string): FileChange[] {
  const records = output.split('\0')
  const files: FileChange[] = []
  for (let index = 0; index < records.length; index++) {
    const status = records[index]
    if (!status) continue
    const path = records[++index]
    if (!path) throw new Error('Missing path in Git name-status')
    if (status.startsWith('R') || status.startsWith('C')) {
      const destination = records[++index]
      if (!destination) throw new Error('Missing destination in Git name-status')
      files.push({ path: destination, originalPath: path, status: changeDescriptions[status[0]] })
    } else files.push({ path, status: changeDescriptions[status[0]] ?? 'Unknown' })
  }
  return files
}

export function printChangedFiles(logger: Logger, changedFiles: FileChange[]) {
  if (changedFiles.length === 0) {
    return
  }
  logger.info('Changed Files:')
  for (const file of changedFiles) {
    let statString = ''
    if (file.insertions !== undefined || file.deletions !== undefined) {
      const ins = file.insertions ?? 0
      const del = file.deletions ?? 0
      statString = ` (+${ins}/-${del})`
    }
    logger.info(`- ${file.status}: ${file.path}${statString}`)
  }
}

export function parseGitDiffNumStat(output: string): Record<string, { insertions: number; deletions: number }> {
  const stats: Array<[string, { insertions: number; deletions: number }]> = []
  const records = output.split('\0')
  for (let index = 0; index < records.length; index++) {
    const record = records[index]
    if (!record) continue
    const [added, removed, ...pathParts] = record.split('\t')
    let path = pathParts.join('\t')
    if (!path) {
      // Rename/copy numstat records have an empty path followed by source and destination.
      index++
      path = records[++index]
    }
    if (!path) throw new Error('Missing path in Git numstat')
    stats.push([
      path,
      { insertions: added === '-' ? 0 : Number.parseInt(added, 10), deletions: removed === '-' ? 0 : Number.parseInt(removed, 10) },
    ])
  }
  return Object.fromEntries(stats)
}

export function parseGitStatus(output: string): FileChange[] {
  return parseGitPorcelain(output).map(({ path, originalPath, indexStatus, workingTreeStatus }) => {
    const statuses: string[] = []
    if (indexStatus !== ' ' && indexStatus !== '?') statuses.push(`${changeDescriptions[indexStatus] ?? 'Changed'} (staged)`)
    if (workingTreeStatus === '?') statuses.push('Untracked')
    else if (workingTreeStatus !== ' ') statuses.push(`${changeDescriptions[workingTreeStatus] ?? 'Changed'} (unstaged)`)
    return { path, ...(originalPath ? { originalPath } : {}), status: statuses.join(', ') }
  })
}

export function getLocalChanges() {
  const statusOutput = execSync('git status --porcelain=v1 -z --untracked-files=all', {
    encoding: 'utf-8',
  })
  const allFiles = parseGitStatus(statusOutput)

  let stagedStats: Record<string, { insertions: number; deletions: number }> = {}
  try {
    const stagedDiffOutput = execSync('git diff --staged --numstat -z --no-color', { encoding: 'utf-8' })
    stagedStats = parseGitDiffNumStat(stagedDiffOutput)
  } catch {
    // Ignore error
  }

  let unstagedStats: Record<string, { insertions: number; deletions: number }> = {}
  try {
    const unstagedDiffOutput = execSync('git diff --numstat -z --no-color', { encoding: 'utf-8' })
    unstagedStats = parseGitDiffNumStat(unstagedDiffOutput)
  } catch {
    // Ignore error
  }

  const stagedFiles: FileChange[] = []
  const unstagedFiles: FileChange[] = []

  for (const file of allFiles) {
    let totalInsertions = 0
    let totalDeletions = 0

    if (file.status.includes('(staged)')) {
      const stats = stagedStats[file.path]
      const stagedFile = { ...file }
      if (stats) {
        stagedFile.insertions = stats.insertions
        stagedFile.deletions = stats.deletions
        totalInsertions += stats.insertions
        totalDeletions += stats.deletions
      }
      stagedFiles.push(stagedFile)
    }

    if (file.status.includes('(unstaged)')) {
      const stats = unstagedStats[file.path]
      const unstagedFile = { ...file }
      if (stats) {
        unstagedFile.insertions = stats.insertions
        unstagedFile.deletions = stats.deletions
        totalInsertions += stats.insertions
        totalDeletions += stats.deletions
      }
      unstagedFiles.push(unstagedFile)
    } else if (file.status.includes('Untracked')) {
      unstagedFiles.push(file)
    }

    if (totalInsertions > 0 || totalDeletions > 0) {
      file.insertions = totalInsertions
      file.deletions = totalDeletions
    }
  }

  return { stagedFiles, unstagedFiles, allFiles }
}

export function createFileStatusPrompt(changedFiles: FileChange[]): string {
  if (changedFiles.length === 0) {
    return ''
  }
  const fileList = changedFiles
    .map((file) => {
      let statString = ''
      if (file.insertions !== undefined || file.deletions !== undefined) {
        const ins = file.insertions ?? 0
        const del = file.deletions ?? 0
        statString = ` (+${ins}/-${del})`
      }
      return `${file.status}: ${file.path}${statString}`
    })
    .join('\n')
  return `<file_status>\n${fileList}\n</file_status>`
}

export const specificReviewSchema = z.object({
  file: z.string(),
  lines: z.string().regex(/^L[1-9]\d*(?:-L[1-9]\d*)?$/),
  review: z.string(),
})

export const reviewOutputSchema = z.object({
  overview: z.string(),
  specificReviews: z.array(specificReviewSchema).optional(),
})

export type ReviewResult = z.infer<typeof reviewOutputSchema>

export function formatReviewForConsole(output: ReviewResult): string {
  let formatted = `### Overview\n\n${output.overview}`

  if (output.specificReviews && output.specificReviews.length > 0) {
    formatted += '\n\n### File-specific feedback\n'
    for (const item of output.specificReviews) {
      formatted += `\n- ${item.file}#${item.lines}\n\n${item.review}\n`
    }
  }
  return formatted
}

type ExecuteCommandFn = (input: CliToolRegistry['executeCommand']['input']) => Promise<CliToolRegistry['executeCommand']['output']>

export const checkGhInstalled = async (executeCommand: ExecuteCommandFn) => {
  const result = await executeCommand({ command: 'gh', args: ['--version'] })
  if (result.exitCode !== 0) {
    throw new MissingDependencyError('gh', 'GitHub CLI (gh) is not installed. Please install it from https://cli.github.com/')
  }
}

export const getDefaultBranch = async (executeCommand: ExecuteCommandFn): Promise<string | undefined> => {
  const branchResult = await executeCommand({
    command: 'gh',
    args: ['repo', 'view', '--json', 'defaultBranchRef', '--jq', '.defaultBranchRef.name'],
  })
  if (branchResult.exitCode === 0) {
    const branch = branchResult.stdout.trim()
    if (branch) {
      return branch
    }
  }

  const defaultBranches = ['master', 'main', 'develop']
  for (const branch of defaultBranches) {
    const result = await executeCommand({
      command: 'git',
      args: ['show-ref', '--verify', '--quiet', `refs/heads/${branch}`],
    })
    if (result.exitCode === 0) {
      return branch
    }
  }

  const remoteResult = await executeCommand({ command: 'git', args: ['remote', 'show', 'origin'] })
  if (remoteResult.exitCode === 0) {
    const match = remoteResult.stdout.match(/HEAD branch: (.*)/)
    if (match?.[1]) {
      return match[1]
    }
  }

  return undefined
}

/**
 * Formats elapsed time in milliseconds to a human-readable string
 * @param ms - Time in milliseconds
 * @returns Formatted time string (e.g., "1.5s", "2m 30s", "1h 15m")
 */
export function formatElapsedTime(ms: number): string {
  const seconds = ms / 1000
  if (seconds < 60) {
    return `${seconds.toFixed(1)}s`
  }

  const minutes = Math.floor(seconds / 60)
  const remainingSeconds = Math.floor(seconds % 60)

  if (minutes < 60) {
    return remainingSeconds > 0 ? `${minutes}m ${remainingSeconds}s` : `${minutes}m`
  }

  const hours = Math.floor(minutes / 60)
  const remainingMinutes = minutes % 60

  return remainingMinutes > 0 ? `${hours}h ${remainingMinutes}m` : `${hours}h`
}

export async function getDefaultContext(
  config: LoadedConfig | undefined,
  commandName?: string,
): Promise<{ context: string; loadRules: Record<string, boolean> | undefined }> {
  const cwd = process.cwd()
  const contextParts: string[] = []

  // Load rules files based on loadRules config (defaults to all enabled for backward compatibility)
  const loadRules = config?.loadRules
  const defaultLoadRules = {
    'AGENTS.md': true,
    'CLAUDE.md': true,
  }
  const mergedRules = { ...defaultLoadRules, ...loadRules }

  // Load each enabled rule file
  for (const [fileName, shouldLoad] of Object.entries(mergedRules)) {
    if (shouldLoad) {
      try {
        const content = await fs.readFile(path.join(cwd, fileName), 'utf-8')
        const tagName = fileName.replace(/\./g, '_')
        contextParts.push(`<${tagName}_instructions>\n${content}\n</${tagName}_instructions>`)
      } catch {
        // Ignore error if file doesn't exist
      }
    }
  }

  let rules = await resolveRules(config?.rules)

  if (commandName && config) {
    const apiConfig = new ApiProviderConfig(config)
    const commandConfig = apiConfig.getConfigForCommand(commandName)
    if (commandConfig?.rules) {
      const commandRules = await resolveRules(commandConfig.rules)
      if (commandRules) {
        rules = rules ? `${rules}\n\n${commandRules}` : commandRules
      }
    }
  }

  if (rules) {
    contextParts.push(`<rules>\n${rules}\n</rules>`)
  }

  return { context: contextParts.join('\n'), loadRules }
}
