// Generated by polka.codes
// Sample TypeScript file for testing tree-sitter parsing

interface User {
  id: number
  name: string
}

class UserService {
  getUser(id: number): User {
    return { id, name: 'test' }
  }
}

function calculateTotal(items: number[]): number {
  return items.reduce((sum, item) => sum + item, 0)
}

const someFunctionWithManyParameters = (
  param1: string,
  param2: number,
  param3: boolean,
  param4: string,
  param5: number,
  param6: boolean,
  param7: string,
  param8: number,
) => {
  return param1 + param2 + param3 + param4 + param5 + param6 + param7 + param8
}
