// Generated by polka.codes

import { afterAll, afterEach, beforeAll, beforeEach, describe, expect, spyOn, test } from 'bun:test'
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { loadConfig, mergeConfigs } from './config'

describe('config', () => {
  let testDir: string
  let testSubDir: string
  let testHomeDir: string

  beforeAll(() => {
    testDir = mkdtempSync(join(tmpdir(), 'polkacodes-test-'))
  })

  beforeEach(() => {
    testSubDir = mkdtempSync(join(testDir, `sub-test-${Math.random()}`))
    testHomeDir = mkdtempSync(join(testDir, `home-test-${Math.random()}`))
    mkdirSync(join(testHomeDir, '.config', 'polkacodes'), { recursive: true })
  })

  afterEach(() => {
    rmSync(testSubDir, { recursive: true, force: true })
    rmSync(testHomeDir, { recursive: true, force: true })
  })

  afterAll(() => {
    rmSync(testDir, { recursive: true, force: true })
  })

  test('loads config from specified path', async () => {
    const configPath = join(testSubDir, 'test-config.yml')
    writeFileSync(
      configPath,
      `
defaultProvider: anthropic
defaultModel: claude-3-opus
    `,
    )

    const config = await loadConfig(configPath, testSubDir, testHomeDir)

    // Verify the config was loaded with the correct values
    expect(config).toBeDefined()
    expect(config?.defaultProvider).toBe('anthropic')
    expect(config?.defaultModel).toBe('claude-3-opus')
  })

  test('loads multiple config files', async () => {
    const configPath1 = join(testSubDir, 'config1.yml')
    const configPath2 = join(testSubDir, 'config2.yml')

    writeFileSync(
      configPath1,
      `
defaultProvider: anthropic
defaultModel: claude-3-opus
rules:
  - rule1
  - rule2
    `,
    )

    writeFileSync(
      configPath2,
      `
defaultModel: claude-3-sonnet
rules:
  - rule3
    `,
    )

    const config = await loadConfig([configPath1, configPath2], testSubDir, testHomeDir)

    // Verify configs are merged with later configs taking precedence
    expect(config).toBeDefined()
    expect(config?.defaultProvider).toBe('anthropic')
    expect(config?.defaultModel).toBe('claude-3-sonnet') // Overridden by config2
    expect(config?.rules).toContain('rule1')
    expect(config?.rules).toContain('rule2')
    expect(config?.rules).toContain('rule3')
  })

  test('loads config from default paths', async () => {
    const configPath = join(testSubDir, '.polkacodes.yml')
    writeFileSync(
      configPath,
      `
defaultProvider: deepseek
defaultModel: deepseek-chat
    `,
    )

    const config = await loadConfig(undefined, testSubDir, testHomeDir)

    // Verify the config was loaded from the default path
    expect(config).toBeDefined()
    expect(config?.defaultProvider).toBe('deepseek')
    expect(config?.defaultModel).toBe('deepseek-chat')

    // Clean up
    writeFileSync(configPath, '')
  })

  test('validates config schema', async () => {
    const consoleErrorSpy = spyOn(console, 'error').mockImplementation(() => {})
    const configPath = join(testSubDir, 'invalid-config.yml')
    writeFileSync(
      configPath,
      `
invalidKey: value
    `,
    )

    expect(loadConfig(configPath, testSubDir, testHomeDir)).rejects.toThrow()
    consoleErrorSpy.mockRestore()
  })

  test('handles commands configuration', async () => {
    const configPath = join(testSubDir, 'commands-config.yml')
    writeFileSync(
      configPath,
      `
scripts:
  test: echo "test"
  complex:
    command: echo "complex"
    description: A complex command
    `,
    )

    const config = await loadConfig(configPath, testSubDir, testHomeDir)

    // Verify scripts are parsed correctly
    expect(config?.scripts).toBeDefined()
    expect(config?.scripts?.test).toBe('echo "test"')
    expect(config?.scripts?.complex).toEqual({
      command: 'echo "complex"',
      description: 'A complex command',
    })
  })

  test('handles rules configuration', async () => {
    const configPath = join(testSubDir, 'rules-config.yml')
    writeFileSync(
      configPath,
      `
rules:
  - rule1
  - rule2
    `,
    )

    const config = await loadConfig(configPath, testSubDir, testHomeDir)

    // Verify rules are parsed as a string
    expect(config?.rules).toBeDefined()
    expect(typeof config?.rules).toBe('string')
    expect(config?.rules).toContain('rule1')
    expect(config?.rules).toContain('rule2')
  })

  test('handles command defaults', async () => {
    const configPath = join(testSubDir, 'defaults-config.yml')
    writeFileSync(
      configPath,
      `
commands:
  default:
    provider: deepseek
    model: deepseek-chat
  task:
    model: deepseek-coder
    `,
    )

    const config = await loadConfig(configPath, testSubDir, testHomeDir)

    // Verify command defaults are parsed correctly
    expect(config?.commands).toBeDefined()
    expect(config?.commands?.default?.provider).toBe('deepseek')
    expect(config?.commands?.default?.model).toBe('deepseek-chat')
    expect(config?.commands?.task?.model).toBe('deepseek-coder')
  })

  test('merges multiple configs correctly', () => {
    const configs = [
      {
        defaultProvider: 'anthropic',
        defaultModel: 'claude-3-opus',
        rules: ['rule1', 'rule2'],
        excludeFiles: ['exclude1'],
      },
      {
        defaultModel: 'claude-3-sonnet',
        rules: ['rule3'],
        excludeFiles: ['exclude2'],
      },
      {
        rules: 'rule4',
        excludeFiles: ['exclude3'],
      },
    ]

    const merged = mergeConfigs(configs)

    // Verify merge behavior: later configs override, arrays concatenate
    expect(merged.defaultProvider).toBe('anthropic')
    expect(merged.defaultModel).toBe('claude-3-sonnet') // Overridden by second config
    expect(merged.rules).toContain('rule1')
    expect(merged.rules).toContain('rule2')
    expect(merged.rules).toContain('rule3')
    expect(merged.rules).toContain('rule4')
    expect(merged.excludeFiles).toEqual(['exclude1', 'exclude2', 'exclude3'])
  })

  test('merges global and local config with local precedence', async () => {
    const globalConfigPath = join(testHomeDir, '.config', 'polkacodes', 'config.yml')
    const localConfigPath = join(testSubDir, '.polkacodes.yml')

    writeFileSync(
      globalConfigPath,
      `
defaultProvider: anthropic
defaultModel: claude-3-opus
commands:
  default:
    provider: deepseek
    model: deepseek-chat
scripts:
  test: echo "global"
  complex:
    command: echo "global-complex"
    description: Global complex command
rules:
  - global-rule
    `,
    )

    writeFileSync(
      localConfigPath,
      `
providers:
  anthropic:
    apiKey: local-key
commands:
  default:
    model: deepseek-coder-instruct
scripts:
  test: echo "local"
rules:
  - local-rule
    `,
    )

    const config = await loadConfig(localConfigPath, testSubDir, testHomeDir)

    // Verify local config takes precedence over global
    expect(config).toBeDefined()
    expect(config?.defaultProvider).toBe('anthropic') // From global
    expect(config?.defaultModel).toBe('claude-3-opus') // From global
    expect(config?.providers?.anthropic?.apiKey).toBe('local-key') // From local
    expect(config?.commands?.default?.provider).toBe('deepseek') // From global
    expect(config?.commands?.default?.model).toBe('deepseek-coder-instruct') // Overridden by local
    expect(config?.scripts?.test).toBe('echo "local"') // Overridden by local
    expect(config?.scripts?.complex).toEqual({
      command: 'echo "global-complex"',
      description: 'Global complex command',
    }) // From global
    expect(config?.rules).toContain('global-rule')
    expect(config?.rules).toContain('local-rule')
  })

  test('concatenates arrays', async () => {
    const globalConfigPath = join(testHomeDir, '.config', 'polkacodes', 'config.yml')
    const localConfigPath = join(testSubDir, '.polkacodes.yml')

    writeFileSync(
      globalConfigPath,
      `
rules:
  - global-rule-1
  - global-rule-2
    `,
    )

    writeFileSync(
      localConfigPath,
      `
rules: local-rule
    `,
    )

    const config = await loadConfig(localConfigPath, testSubDir, testHomeDir)

    // Verify array concatenation behavior
    expect(config?.rules).toBeDefined()
    expect(config?.rules).toContain('global-rule-1')
    expect(config?.rules).toContain('global-rule-2')
    expect(config?.rules).toContain('local-rule')
  })

  test('parses project .polkacodes.yml successfully', async () => {
    await loadConfig()
  })

  test('parses example.polkacodes.yml successfully', async () => {
    const fetchSpy = spyOn(global, 'fetch').mockImplementation((() => Promise.resolve(new Response('mock rule content'))) as any)
    try {
      await loadConfig('example.polkacodes.yml')
    } finally {
      fetchSpy.mockRestore()
    }
  })

  test('handles both string and array rules formats', async () => {
    // Test string format
    const stringConfigPath = join(testSubDir, 'string-rules.yml')
    writeFileSync(
      stringConfigPath,
      `
rules: |
  Rule 1
  Rule 2
  Rule 3
      `,
    )
    const stringConfig = await loadConfig(stringConfigPath, testSubDir, testHomeDir)
    expect(typeof stringConfig?.rules).toBe('string')
    expect(stringConfig?.rules).toContain('Rule 1')

    // Test array format
    const arrayConfigPath = join(testSubDir, 'array-rules.yml')
    writeFileSync(
      arrayConfigPath,
      `
rules:
  - "Rule 1"
  - "Rule 2"
  - "Rule 3"
      `,
    )
    const arrayConfig = await loadConfig(arrayConfigPath, testSubDir, testHomeDir)
    expect(typeof arrayConfig?.rules).toBe('string')
    expect(arrayConfig?.rules).toContain('Rule 1')
    expect(arrayConfig?.rules).toContain('Rule 2')
    expect(arrayConfig?.rules).toContain('Rule 3')

    // Test merging behavior
    const globalConfigPath = join(testHomeDir, '.config', 'polkacodes', 'config.yml')
    const localConfigPath = join(testSubDir, 'merged-rules.yml')

    writeFileSync(
      globalConfigPath,
      `
rules:
  - "Global Rule 1"
  - "Global Rule 2"
      `,
    )

    writeFileSync(
      localConfigPath,
      `
rules: "Local Rule"
      `,
    )

    const mergedConfig = await loadConfig(localConfigPath, testSubDir, testHomeDir)
    expect(typeof mergedConfig?.rules).toBe('string')
    expect(mergedConfig?.rules).toContain('Global Rule 1')
    expect(mergedConfig?.rules).toContain('Global Rule 2')
    expect(mergedConfig?.rules).toContain('Local Rule')
  })
})
