/**
 * Tests for generateProjectConfig AiTool
 * Generated by polka.codes
 */

import { describe, expect, test } from 'bun:test'
import generateProjectConfig from './generateProjectConfig'

describe('generateProjectConfig', () => {
  test('should format input correctly', () => {
    const files = {
      'package.json': '{"scripts": {"test": "bun test"}}',
      '.polkacodes.yml': 'rules: ["Use bun"]',
    }

    const input = generateProjectConfig.formatInput({ files })
    expect(input).toMatchSnapshot()
  })

  test('should parse output correctly', () => {
    const output = `<tool_output>
scripts:
  test:
    command: "bun test"
    description: "Run tests"

rules:
  - "Use bun as package manager"
</tool_output>`

    const result = generateProjectConfig.parseOutput(output)
    expect(result).toMatchSnapshot()
  })

  test('should throw error on invalid output', () => {
    const output = 'Invalid output without tool_output tags'
    expect(() => generateProjectConfig.parseOutput(output)).toThrow()
  })
})
