/**
 * AI tool for analyzing project files and generating polkacodes config sections.
 * Generated by polka.codes
 */

import type { AiToolDefinition } from './types'

const prompt = `You are an analyzer agent responsible for examining project files and generating appropriate polkacodes configuration. Your task is to:

1. Read and analyze the provided files using tool_read_file to understand:
   - Build tools and package manager (e.g., bun, npm)
   - Testing frameworks and patterns
   - Code style tools and rules
   - Project structure and conventions
   - Common development workflows

2. Generate a YAML configuration that captures:
   - scripts section based on package.json scripts and CI workflows. If applicable, generate following scripts:
     - format: Format the code using a code formatter tool
     - check: Check the code for errors using a linter tool
     - test: Run tests using a test runner tool
   - include other relevant scripts based on project conventions, tools, and patterns
   - rules section based on project conventions, tools, and patterns
   - excludeFiles section for sensitive files

3. Use tool_attempt_completion to return the final configuration in this format:

<tool_attempt_completion>
<tool_parameter_result>
scripts:
  test:
    command: "bun test"
    description: "Run tests with bun:test"
  lint:
    command: "biome check ."
    description: "Check code style with Biome"

rules:
  - "Use \`bun\` as package manager"
  - "Write tests using bun:test with snapshots"
  - "Follow Biome code style"

excludeFiles:
  # Sensitive files
  - ".env"
  - ".env.*"
  - ".npmrc"
</tool_parameter_result>
</tool_attempt_completion>

Focus on:
- Package manager and dependency management
- Testing frameworks and patterns
- Code style and linting rules
- File organization and naming conventions
- Build and development workflows
- Sensitive files that should not be committed:
  - Environment files (.env*)
  - Configuration files with potential secrets
- Generated files to exclude:
  - Lock files from package managers
  - Build artifacts and outputs
  - Generated file that are not ignored by .gitignore

The configuration should accurately reflect the project's structure, tools, and conventions.
`

export default {
  name: 'generateProjectConfig',
  description: 'Analyzes project files to generate polkacodes config sections',
  prompt,
  formatInput: () => {
    return ''
  },
  parseOutput: (output: string) => {
    return output
  },
  agent: 'analyzer',
} as const satisfies AiToolDefinition<void>
