// generated by polka.codes
import { describe, expect, it } from 'bun:test'
import { z } from 'zod'
import { AiProvider, getModel } from './getModel'
import { getProviderOptions } from './getProviderOptions'

describe('getModel', () => {
  it('should create Anthropic model', () => {
    const model = getModel({
      provider: AiProvider.Anthropic,
      model: 'claude-3-5-sonnet-20241022',
      apiKey: 'test-key',
    })

    expect(model).toBeDefined()
    expect(model.modelId).toBe('claude-3-5-sonnet-20241022')
  })

  it('should create OpenAI model', () => {
    const model = getModel({
      provider: AiProvider.OpenAI,
      model: 'gpt-4',
      apiKey: 'test-key',
    })

    expect(model).toBeDefined()
    expect(model.modelId).toBe('gpt-4')
  })

  it('should create Google model', () => {
    const model = getModel({
      provider: AiProvider.Google,
      model: 'gemini-2.0-flash-exp',
      apiKey: 'test-key',
    })

    expect(model).toBeDefined()
  })

  it('should create Google Vertex model', () => {
    const model = getModel({
      provider: AiProvider.GoogleVertex,
      model: 'gemini-2.0-flash-exp',
      project: 'test-project',
      location: 'us-central1',
    })

    expect(model).toBeDefined()
  })

  it('should create DeepSeek model', () => {
    const model = getModel({
      provider: AiProvider.DeepSeek,
      model: 'deepseek-chat',
      apiKey: 'test-key',
    })

    expect(model).toBeDefined()
  })

  it('should create OpenRouter model', () => {
    const model = getModel({
      provider: AiProvider.OpenRouter,
      model: 'anthropic/claude-3.5-sonnet',
      apiKey: 'test-key',
    })

    expect(model).toBeDefined()
  })

  it('should create OpenAI-compatible model', () => {
    const model = getModel({
      provider: AiProvider.OpenAICompatible,
      model: 'gpt-4o',
      apiKey: 'test-key',
      baseUrl: 'https://api.together.xyz/v1',
    })

    expect(model).toBeDefined()
    expect(model.modelId).toBe('gpt-4o')
  })

  it('should reject unsupported providers', () => {
    expect(() =>
      getModel({
        provider: 'unsupported' as AiProvider,
        model: 'test-model',
      }),
    ).toThrow('Unsupported AI provider: unsupported')
  })

  it.each([
    [AiProvider.Anthropic, 'claude-sonnet-4-20250514'],
    [AiProvider.Anthropic, 'custom-model-alias'],
    [AiProvider.OpenRouter, 'anthropic/claude-sonnet-4'],
    [AiProvider.OpenRouter, 'anthropic/custom-model-alias'],
    [AiProvider.OpenRouter, 'google/gemini-2.5-pro'],
  ] as const)('preserves explicit thinking configuration for %s / %s', async (provider, modelId) => {
    const bodySchema = z.object({ model: z.string(), thinking: z.json().optional(), reasoning: z.json().optional() })
    const requests: { headers: Headers; body: z.infer<typeof bodySchema> }[] = []
    const directAnthropic = provider === AiProvider.Anthropic
    const server = Bun.serve({
      hostname: '127.0.0.1',
      port: 0,
      async fetch(request) {
        requests.push({ headers: request.headers, body: bodySchema.parse(await request.json()) })
        return Response.json(
          directAnthropic
            ? {
                id: 'test-response',
                type: 'message',
                role: 'assistant',
                model: modelId,
                content: [{ type: 'text', text: 'Done.' }],
                stop_reason: 'end_turn',
                stop_sequence: null,
                usage: { input_tokens: 1, output_tokens: 1 },
              }
            : {
                id: 'test-response',
                model: modelId,
                choices: [{ index: 0, message: { role: 'assistant', content: 'Done.' }, finish_reason: 'stop' }],
                usage: { prompt_tokens: 1, completion_tokens: 1, total_tokens: 2 },
              },
        )
      },
    })
    try {
      const model = getModel({ provider, model: modelId, apiKey: 'test-key', baseUrl: server.url.href })
      for (const thinkingBudgetTokens of [undefined, 8192]) {
        await model.doGenerate({
          prompt: [{ role: 'user', content: [{ type: 'text', text: 'Hello.' }] }],
          maxOutputTokens: 16384,
          providerOptions: getProviderOptions({ provider, modelId, parameters: { thinkingBudgetTokens }, supportThinking: true }),
        })
      }

      expect(requests).toHaveLength(2)
      expect(requests[0].body).toEqual({ model: modelId })
      expect(requests[1].body).toEqual({
        model: modelId,
        ...(directAnthropic ? { thinking: { type: 'enabled', budget_tokens: 8192 } } : { reasoning: { max_tokens: 8192 } }),
      })
      for (const { headers } of requests) {
        if (directAnthropic) {
          expect(headers.get('anthropic-beta')?.split(',')).toContain('interleaved-thinking-2025-05-14')
          expect(headers.has('x-anthropic-beta')).toBe(false)
          expect(headers.get('x-api-key')).toBe('test-key')
        } else {
          expect(headers.get('x-anthropic-beta')).toBe(modelId.startsWith('anthropic/') ? 'interleaved-thinking-2025-05-14' : null)
          expect(headers.has('anthropic-beta')).toBe(false)
          expect(headers.get('authorization')).toBe('Bearer test-key')
          expect(headers.get('http-referer')).toBe('https://polka.codes')
          expect(headers.get('x-title')).toBe('Polka Codes')
        }
      }
    } finally {
      server.stop(true)
    }
  })
})
