// generated by polka.codes
import { z } from 'zod'
import type { SkillContext } from '../types.js'

/**
 * Tool input parameters for listing skills
 */
export const ListSkillsInputSchema = z.object({
  filter: z.string().optional().describe('Filter by skill name or description.'),
})

export type ListSkillsInput = z.infer<typeof ListSkillsInputSchema>

/**
 * Tool output for listing skills
 */
export const ListSkillsOutputSchema = z.object({
  skills: z.array(
    z.object({
      name: z.string(),
      description: z.string(),
      source: z.enum(['personal', 'project', 'plugin']),
    }),
  ),
  total: z.number(),
})

export type ListSkillsOutput = z.infer<typeof ListSkillsOutputSchema>

/**
 * List all available skills with their descriptions
 *
 * This tool enables agents to discover what specialized capabilities
 * are available based on task context.
 */
export async function listSkills(input: ListSkillsInput, context: SkillContext): Promise<ListSkillsOutput> {
  const { filter } = input
  let skills = context.availableSkills

  // Apply filter if provided
  if (filter) {
    const filterLower = filter.toLowerCase()
    skills = skills.filter((s) => s.metadata.name.includes(filterLower) || s.metadata.description.toLowerCase().includes(filterLower))
  }

  return {
    skills: skills.map((s) => ({
      name: s.metadata.name,
      description: s.metadata.description,
      source: s.source,
    })),
    total: skills.length,
  }
}

/**
 * Tool info for listSkills (used in agent workflow)
 */
export const listSkillsToolInfo = {
  name: 'listSkills',
  description: 'List available skills, optionally filtered by name or description. Use when the required skill name is unknown.',
  parameters: ListSkillsInputSchema,
  returns: ListSkillsOutputSchema,
} as const
