/**
 * Tests for the delegate tool
 * Generated by polka.codes
 */

import { describe, expect, test } from 'bun:test'
import { ToolResponseType } from '../tool'
import { handler } from './delegate'

describe('delegate tool', () => {
  test('handler should return proper delegate response', async () => {
    const result = await handler(
      {},
      {
        agentName: 'analyzer',
        task: 'analyze code',
        context: 'test context',
        files: 'file1.ts,file2.ts',
      },
    )

    expect(result).toEqual({
      type: ToolResponseType.Delegate,
      agentName: 'analyzer',
      task: 'analyze code',
      context: 'test context',
      files: ['file1.ts', 'file2.ts'],
    })
  })

  test('handler should return invalid if required parameters are missing', async () => {
    const result = await handler({}, {})
    expect(result.type).toBe(ToolResponseType.Invalid)
  })
})
