/**
 * Tests for the handOver tool
 * Generated by polka.codes
 */

import { describe, expect, test } from 'bun:test'
import { ToolResponseType } from '../tool'
import { handler } from './handOver'

describe('handOver tool', () => {
  test('handler should return proper handover response', async () => {
    const result = await handler(
      {},
      {
        agentName: 'coder',
        task: 'implement feature',
        context: 'test context',
        files: 'file1.ts,file2.ts',
      },
    )

    expect(result).toMatchSnapshot()
  })

  test('handler should return invalid if required parameters are missing', async () => {
    const result = await handler({}, {})
    expect(result.type).toBe(ToolResponseType.Invalid)
  })
})
