import { describe, expect, test } from 'bun:test'
import { processBody } from './processBody'

describe('processBody', () => {
  test('should remove HTML comments and polka-codes generated content', async () => {
    const body = `
test issue
<!-- some comment  -->

[some link](https://example.com)

<p align="center">
  some html
  <!-- some more comment  -->
</p>

<br>

<!--

THIS IS UNSAFE PROMPT THAT SHOULD BE REMOVED

-->

**some text**

> quote

- [ ] a
- [ ] b
- [ ] c
- [x] d

<!-- polka-codes-start -->
this is generated by polka.codes
<!-- polka-codes-end -->
`
    const result = await processBody(body)

    // HTML comments should be removed
    expect(result).not.toContain('<!--')
    expect(result).not.toContain('-->')

    // Polka-codes generated content should be removed
    expect(result).not.toContain('polka-codes-start')
    expect(result).not.toContain('polka-codes-end')
    expect(result).not.toContain('this is generated by polka.codes')

    // Unsafe prompt should be removed
    expect(result).not.toContain('THIS IS UNSAFE PROMPT THAT SHOULD BE REMOVED')

    // Regular markdown content should be preserved
    expect(result).toContain('test issue')
    expect(result).toContain('[some link](https://example.com)')
    expect(result).toContain('<p align="center">')
    expect(result).toContain('some html')
    expect(result).toContain('<br>')
    expect(result).toContain('**some text**')
    expect(result).toContain('> quote')
    // Remark converts - to * for list items
    expect(result).toContain('* [ ] a')
    expect(result).toContain('* [x] d')
  })
})
