import { describe, expect, test } from 'bun:test'
import { processBody } from './processBody'

describe('processBody', () => {
  test('should process body', async () => {
    const body = `
test issue
<!-- some comment  -->

[some link](https://example.com)

<p align="center">
  some html
  <!-- some more comment  -->
</p>

<br>

<!--

THIS IS UNSAFE PROMPT THAT SHOULD BE REMOVED

-->

**some text**

> quote

- [ ] a
- [ ] b
- [ ] c
- [x] d

<!-- polka-codes-start -->
this is generated by polka.codes
<!-- polka-codes-end -->
`
    const result = await processBody(body)
    expect(result).toMatchSnapshot()
  })
})
