// generated by polka.codes
import { z } from 'zod'

/**
 * Zod schema for skill metadata (YAML frontmatter in SKILL.md)
 */
export const skillMetadataSchema = z.object({
  name: z
    .string()
    .regex(/^[a-z0-9-]+$/, 'Skill name must be lowercase letters, numbers, and hyphens')
    .max(64, 'Skill name must be at most 64 characters'),
  description: z.string().max(1024, 'Description must be at most 1024 characters'),
  allowedTools: z.array(z.string()).optional(),
})

export type SkillMetadata = z.infer<typeof skillMetadataSchema>

/**
 * Represents a loaded Agent Skill with all its content
 */
export interface Skill {
  /**
   * Parsed metadata from SKILL.md frontmatter
   */
  metadata: SkillMetadata

  /**
   * Main instructions content (SKILL.md without frontmatter)
   */
  content: string

  /**
   * Additional files bundled with the skill
   * Key is relative path from skill directory (e.g., "reference.md", "scripts/helper.py")
   * Value is file content
   */
  files: Map<string, string>

  /**
   * Absolute path to the skill directory on disk
   */
  path: string

  /**
   * Where the skill was loaded from
   */
  source: 'personal' | 'project' | 'plugin'
}

/**
 * Context object passed to agents and tools for skill operations
 */
export interface SkillContext {
  /**
   * Currently active/loaded skill (if any)
   */
  activeSkill: Skill | null

  /**
   * All available skills discovered from all sources
   */
  availableSkills: Skill[]

  /**
   * History of skills loaded during the session (for debugging/telemetry)
   */
  skillLoadingHistory: string[]
}

/**
 * Error thrown when skill discovery fails
 */
export class SkillDiscoveryError extends Error {
  constructor(
    message: string,
    public path: string,
  ) {
    super(message)
    this.name = 'SkillDiscoveryError'
  }
}

/**
 * Error thrown when skill validation fails
 */
export class SkillValidationError extends Error {
  constructor(
    message: string,
    public path: string,
  ) {
    super(message)
    this.name = 'SkillValidationError'
  }
}
