name: Issue Handler

on:
  issues:
    types: [opened, labeled]
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to process'
        required: true
        type: number

env:
  POLKA_API_PROVIDER: openrouter
  POLKA_MODEL: deepseek/deepseek-chat
  POLKA_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
  GH_TOKEN: ${{ github.token }}

jobs:
  handle:
    if: |
      (github.event_name == 'issues' && contains(github.event.issue.labels.*.name, 'polka.codes')) ||
      github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Process issue and format task
        id: process
        uses: actions/github-script@v7
        with:
          script: |
            const handler = require('./.github/workflows/scripts/issue-handler.js');

            try {
              const issueData = await handler.getIssueData(github, context, context.payload.inputs);
              const taskString = handler.formatTask(issueData);
              const escapedTask = handler.escapeGitHubOutput(taskString);

              core.setOutput('task', escapedTask);
            } catch (error) {
              core.setFailed(`Failed to process issue: ${error.message}`);
              throw error;
            }

      - name: Run polka.codes CLI
        run: |
          echo "${{ steps.process.outputs.task }}"
          echo "${{ steps.process.outputs.task }}" | bun cli

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b polka-codes/issue-${{ github.event.issue.number }}
          bun cli commit -a
          bun cli pr

# Generated by polka.codes
