name: Polka Codes PR Handler

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to process'
        required: true
        type: number

permissions:
  contents: write # required for push commit
  pull-requests: write # required for create pr

concurrency:
  group: pr-${{ github.event.inputs.pr_number }}
  cancel-in-progress: true

jobs:
  handle:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Config git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Process PR
        uses: polka-codes/action@master
        with:
          pr_number: ${{ github.event.inputs.pr_number }}
          config: .polkacodes.yml,ci.polkacodes.yml
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GITHUB_TOKEN: ${{ github.token }}

# Generated by polka.codes
